# Copyright (c) 2025-2026 SandAI. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from dataclasses import dataclass, field

import torch
from torch.nn.attention.flex_attention import create_block_mask

from magi_attention import env
from magi_attention.common import AttnRanges
from magi_attention.common.enum import MagiAttentionKernelBackend
from magi_attention.common.range import AttnRange
from magi_attention.utils import (
    format_dict_field,
    format_list_field,
    make_attn_mask_from_ffa_args,
    nvtx,
)

_DEFAULT_FA4_TILE_SIZE = (128, 128)

is_magi_to_hstu_installed = False
try:
    import create_block_mask_cuda
    import magi_to_hstu_cuda

    is_magi_to_hstu_installed = True
except ImportError:
    pass

is_fa4_installed = False
try:
    from flash_attn_cute.block_sparsity import (
        BlockSparseTensorsTorch,
        LinearBlockSparseTensorsTorch,
        bhqk_to_linear_sparse_tensors,
    )

    is_fa4_installed = True
except ImportError:
    pass

# Optional: only needed for FA4AttnArg.compute_mask with arbitrary masks
try:
    from flash_attn_cute.mask_definitions import flex_arbitrary_mask
except ImportError:
    flex_arbitrary_mask = None  # type: ignore[assignment]

try:
    COMPUTE_CAPABILITY = torch.cuda.get_device_capability()[0]
except Exception:
    COMPUTE_CAPABILITY = 10


@dataclass(repr=False)
class AttnArg:
    q_ranges: AttnRanges
    k_ranges: AttnRanges
    attn_type_map: list[int]

    # total area of the attn arg, -1 means unknown
    total_area: int = -1

    # NOTE: The following variables are automatically generated by `__post_init__`
    # and serve as the meta arguments for ffa kernels in dist-attn.
    #   ffa_fwd_args_dict: dict
    #   skip_attn_fwd: bool
    #   disable_fwd_atomic_reduction: bool
    #
    #   q_ranges_bwd: AttnRanges
    #   k_ranges_bwd: AttnRanges
    #   attn_type_map_bwd: list[int]
    #   ffa_bwd_args_dict: dict
    #   skip_attn_bwd: bool
    #   disable_bwd_dkv_atomic_reduction: bool

    def __post_init__(self):
        # shape check
        assert len(self.q_ranges) == len(self.k_ranges) == len(self.attn_type_map)

        # init fwd ffa args dict
        # NOTE: we need to init fwd args first before bwd args
        self._init_ffa_fwd_args_dict()

        # init ffa args for bwd
        self._init_ffa_bwd_args_dict()

    def _init_ffa_fwd_args_dict(self) -> None:
        # init `skip_attn_fwd` flag
        batch_size_fwd = len(self.q_ranges)
        self.skip_attn_fwd = batch_size_fwd == 0

        # guard clause
        if self.skip_attn_fwd:
            self.ffa_fwd_args_dict = {}
            return

        # init `disable_fwd_atomic_reduction` flag
        self.disable_fwd_atomic_reduction = self.q_ranges.is_non_overlap()

        # init tensors
        q_ranges_tensor_fwd = self.q_ranges.to_tensor(
            device=torch.cuda.current_device()
        )
        k_ranges_tensor_fwd = self.k_ranges.to_tensor(
            device=torch.cuda.current_device()
        )
        mask_type_tensor_fwd = torch.tensor(
            self.attn_type_map,
            dtype=torch.int32,
            device=torch.cuda.current_device(),
        )

        # sanity check
        if env.general.is_sanity_check_enable():
            # check tensor shape
            if not self.skip_attn_fwd:
                assert q_ranges_tensor_fwd.shape == torch.Size([batch_size_fwd, 2])
                assert k_ranges_tensor_fwd.shape == torch.Size([batch_size_fwd, 2])
                assert mask_type_tensor_fwd.shape == torch.Size([batch_size_fwd])

        if env.general.is_auto_range_merge_enable():
            # lazy import to avoid circular import
            from magi_attention.functional.flex_flash_attn import merge_ranges

            # merge q_ranges to reduce the number of unique ranges
            (
                merge_q_ranges,
                q_ranges_tensor_fwd,
                k_ranges_tensor_fwd,
                mask_type_tensor_fwd,
                fwd_qk_map,
                fwd_unique_count,
            ) = merge_ranges(
                q_ranges_tensor_fwd,
                k_ranges_tensor_fwd,
                attn_type_map=mask_type_tensor_fwd,
            )

            self.ffa_fwd_args_dict = dict(
                merge_q_ranges=merge_q_ranges,
                q_ranges=q_ranges_tensor_fwd,
                k_ranges=k_ranges_tensor_fwd,
                attn_type_map=mask_type_tensor_fwd,
                fwd_qk_map=fwd_qk_map,
                fwd_unique_count=fwd_unique_count,
            )
        else:
            self.ffa_fwd_args_dict = dict(
                q_ranges=q_ranges_tensor_fwd,
                k_ranges=k_ranges_tensor_fwd,
                attn_type_map=mask_type_tensor_fwd,
            )

    def _init_ffa_bwd_args_dict(self) -> None:
        # just copy args from fwd
        self.skip_attn_bwd = self.skip_attn_fwd
        self.q_ranges_bwd = self.q_ranges
        self.k_ranges_bwd = self.k_ranges
        self.attn_type_map_bwd = self.attn_type_map

        # guard clause
        if self.skip_attn_bwd:
            self.ffa_bwd_args_dict = {}
            return

        q_ranges_tensor_bwd = self.q_ranges_bwd.to_tensor(
            device=torch.cuda.current_device()
        )
        k_ranges_tensor_bwd = self.k_ranges_bwd.to_tensor(
            device=torch.cuda.current_device()
        )
        attn_type_map = torch.tensor(
            self.attn_type_map_bwd,
            dtype=torch.int32,
            device=torch.cuda.current_device(),
        )

        # sanity check
        if env.general.is_sanity_check_enable():
            # check tensor shape
            batch_size_bwd = len(self.q_ranges_bwd)
            if not self.skip_attn_bwd:
                assert q_ranges_tensor_bwd.shape == torch.Size([batch_size_bwd, 2])
                assert k_ranges_tensor_bwd.shape == torch.Size([batch_size_bwd, 2])
                assert attn_type_map.shape == torch.Size([batch_size_bwd])

        if env.general.is_auto_range_merge_enable():
            # lazy import to avoid circular import
            from magi_attention.functional.flex_flash_attn import merge_ranges

            # merge k_ranges to reduce the number of unique ranges
            (
                merge_k_ranges,
                k_ranges_tensor_bwd,
                q_ranges_tensor_bwd,
                mask_type_tensor_bwd,
                bwd_kq_map,
                bwd_unique_count,
            ) = merge_ranges(
                k_ranges_tensor_bwd, q_ranges_tensor_bwd, attn_type_map=attn_type_map
            )

            self.ffa_bwd_args_dict = dict(
                merge_k_ranges=merge_k_ranges,
                q_ranges=q_ranges_tensor_bwd,
                k_ranges=k_ranges_tensor_bwd,
                attn_type_map=mask_type_tensor_bwd,
                bwd_kq_map=bwd_kq_map,
                bwd_unique_count=bwd_unique_count,
            )
        else:
            self.ffa_bwd_args_dict = dict(
                q_ranges=q_ranges_tensor_bwd,
                k_ranges=k_ranges_tensor_bwd,
                attn_type_map=attn_type_map,
            )

        # init `disable_bwd_dkv_atomic_reduction` flag
        # NOTE: this flag only considers the non-overlapping and sorted of k ranges,
        # but it can only be enabled with MHA or GQA/MQA with special configuration (e.g., CatGQA)
        # thus requiring the upper level logic to decide whether to enable it actually
        # curently we only enable it when k_ranges is non-overlapping and sorted, and CatGQA is enabled
        self.disable_bwd_dkv_atomic_reduction = (
            self.k_ranges_bwd.is_non_overlap()
            and self.k_ranges_bwd.is_sorted()
            and env.general.is_cat_gqa_enable()
            # TODO: support auto range merge:
            #  when enabled, we should use the merged k_ranges above
        ) and not env.general.is_auto_range_merge_enable()

    def to_ffa_args(self, is_bwd: bool = False) -> dict:
        return self.ffa_bwd_args_dict if is_bwd else self.ffa_fwd_args_dict

    def can_skip(self, is_bwd: bool = False) -> bool:
        return self.skip_attn_bwd if is_bwd else self.skip_attn_fwd

    def __repr__(self) -> str:  # pragma: no cover
        indent = ""
        repr_str = "AttnArg(\n"

        repr_str += f"{indent}    q_ranges={repr(self.q_ranges)},\n"
        repr_str += f"{indent}    k_ranges={repr(self.k_ranges)},\n"
        repr_str += f"{indent}    attn_type_map={self.attn_type_map},\n"
        repr_str += f"{indent}    total_area={self.total_area},\n"

        repr_str += f"{indent}    # Generated by __post_init__ (fwd):\n"
        repr_str += format_dict_field(
            "ffa_fwd_args_dict", self.ffa_fwd_args_dict, indent
        )
        repr_str += f"{indent}    skip_attn_fwd={self.skip_attn_fwd},\n"
        repr_str += f"{indent}    disable_fwd_atomic_reduction={self.disable_fwd_atomic_reduction},\n"

        repr_str += f"{indent}    # Generated by __post_init__ (bwd):\n"
        repr_str += f"{indent}    q_ranges_bwd={repr(self.q_ranges_bwd)},\n"
        repr_str += f"{indent}    k_ranges_bwd={repr(self.k_ranges_bwd)},\n"
        repr_str += f"{indent}    attn_type_map_bwd={self.attn_type_map_bwd},\n"
        repr_str += format_dict_field(
            "ffa_bwd_args_dict", self.ffa_bwd_args_dict, indent
        )
        repr_str += f"{indent}    skip_attn_bwd={self.skip_attn_bwd},\n"
        repr_str += f"{indent}    disable_bwd_dkv_atomic_reduction={self.disable_bwd_dkv_atomic_reduction},\n"

        repr_str = repr_str.rstrip(",\n") + "\n)"
        return repr_str


def _resolve_tile_sizes(pass_type: str, headdim: int = 128) -> tuple[int, int]:
    """Resolve the correct **mask** tile sizes for the current GPU architecture.

    On SM100 (Blackwell) the base mask tile is 128x128. Forward uses a
    q-stage-dependent Q2K block. Backward K2Q granularity is path-specific:
    the 128/128 and 192/128 2CTA paths use 128x256, while the dedicated
    256/256 path uses 256x128.

    On SM80/SM90, the tile sizes depend on ``headdim`` and are queried
    from the C++ (hopper) backend via ``get_tile_sizes_by_backend``.
    """
    if COMPUTE_CAPABILITY >= 10:
        return _DEFAULT_FA4_TILE_SIZE

    try:
        from flash_attn_cute.utils import get_tile_sizes_by_backend

        return get_tile_sizes_by_backend(
            pass_type=pass_type,
            headdim=headdim,
            is_arbitrary=True,
        )
    except ImportError:
        return _DEFAULT_FA4_TILE_SIZE


@dataclass(repr=False)
class FA4AttnArg(AttnArg):
    tile_m: int = -1
    tile_n: int = -1
    tile_m_bwd: int = -1
    tile_n_bwd: int = -1
    seqlen_q: int = 0
    seqlen_k: int = 0
    headdim: int = 128
    headdim_v: int | None = None
    # Q-heads-per-KV-head ratio (== num_heads_q / num_heads_kv). Needed so we can
    # compute the same fwd `q_stage` as the FA cute backend uses, and build the
    # block-sparse mask at a matching Q granularity.
    qhead_per_kvhead: int = 1

    def __post_init__(self):
        assert is_fa4_installed, "FlashAttn4 is not installed"
        assert is_magi_to_hstu_installed, "magi_to_hstu_cuda is not installed"
        if self.headdim_v is None:
            self.headdim_v = self.headdim

        # DEVIATION: sentinel tile sizes (-1) are replaced with arch-specific defaults
        # Reason: -1 is a user-facing sentinel meaning "auto-detect"; the kernel
        #   requires concrete tile sizes resolved from the current GPU architecture.
        # Recovery: none — sentinel is designed to be replaced.
        if self.tile_m == -1 or self.tile_n == -1:
            fwd_tile_m, fwd_tile_n = _resolve_tile_sizes("forward", self.headdim)
            if self.tile_m == -1:
                self.tile_m = fwd_tile_m
            if self.tile_n == -1:
                self.tile_n = fwd_tile_n

        if self.tile_m_bwd == -1 or self.tile_n_bwd == -1:
            bwd_tile_m, bwd_tile_n = _resolve_tile_sizes("backward", self.headdim)
            if self.tile_m_bwd == -1:
                self.tile_m_bwd = bwd_tile_m
            if self.tile_n_bwd == -1:
                self.tile_n_bwd = bwd_tile_n

        if COMPUTE_CAPABILITY >= 10 and (
            (self.tile_m, self.tile_n) != _DEFAULT_FA4_TILE_SIZE
            or (self.tile_m_bwd, self.tile_n_bwd) != _DEFAULT_FA4_TILE_SIZE
        ):
            raise ValueError(
                f"FA4 mask tile size on SM {COMPUTE_CAPABILITY}.0 must be "
                f"{_DEFAULT_FA4_TILE_SIZE}, got fwd=({self.tile_m}, {self.tile_n}), "
                f"bwd=({self.tile_m_bwd}, {self.tile_n_bwd}). "
                f"The SM100 kernel internally expands the linear CSR block size."
            )

        super().__post_init__()

        # Transfer from FFA args to FA4 args
        self._transfer_ffa_args_to_fa4_args()

        # Clear FFA args
        self.ffa_fwd_args_dict.clear()
        self.ffa_bwd_args_dict.clear()

    def _make_fa4_args_dict(
        self,
        hstu_func: torch.Tensor,
        aux_tensors: list[torch.Tensor],
        tile_m: int,
        tile_n: int,
    ) -> dict:
        # Match FA cute backend's `q_stage` heuristic exactly so the sparse mask
        # we build lines up with `base_m_block = q_stage * tile_m` on the kernel
        # side (otherwise infer_linear_block_sparse_expected_shapes rejects us).
        if COMPUTE_CAPABILITY == 10:
            seqlen_q_packgqa = self.seqlen_q * self.qhead_per_kvhead
            q_stage_fwd = 2 if seqlen_q_packgqa > tile_m else 1
        else:
            q_stage_fwd = 1
        sparse_tile_m = q_stage_fwd * tile_m
        if COMPUTE_CAPABILITY in (10, 11) and (
            (self.headdim, self.headdim_v) in ((128, 128), (192, 128))
        ):
            # The two CTAs form a cluster along N only. Each K2Q CSR Q index
            # therefore maps directly to one M tile.
            bwd_sparse_tile_m = tile_m
            bwd_sparse_tile_n = 2 * tile_n
        elif COMPUTE_CAPABILITY == 10 and (
            self.headdim,
            self.headdim_v,
        ) == (256, 256):
            bwd_sparse_tile_m = 2 * tile_m
            bwd_sparse_tile_n = tile_n
        else:
            bwd_sparse_tile_m = tile_m
            bwd_sparse_tile_n = tile_n

        if is_magi_to_hstu_installed:
            with nvtx.add_nvtx_event(
                f"create_q2k_csr_sparse_from_func-"
                f"seqlen_q={self.seqlen_q}-seqlen_k={self.seqlen_k}-"
                f"tile_m={tile_m}-tile_n={tile_n}"
            ):
                # Q2K (Forward): fix q_block, loop kv_blocks
                (
                    cuda_k_mask_cnt,
                    cuda_k_mask_offset,
                    cuda_k_mask_idx,
                    cuda_k_full_cnt,
                    cuda_k_full_offset,
                    cuda_k_full_idx,
                ) = create_block_mask_cuda.create_q2k_csr_sparse_from_func(
                    hstu_func,
                    self.seqlen_q,
                    self.seqlen_k,
                    Q_BLOCK_SIZE=sparse_tile_m,
                    KV_BLOCK_SIZE=tile_n,
                    check_q_boundary=False,
                )

                # Convert to LinearBlockSparseTensorsTorch format
                # CUDA kernel returns:
                #   - cnt: [B, H, num_blocks] - kept 3D for FA-cute (>=v1.1.1) expected layout
                #   - offset: [B * H * num_blocks + 1] - flattened exclusive prefix sum (starts with 0)
                #   - idx: [total_blocks] - compact indices
                linear_k_block_sparse_mask = LinearBlockSparseTensorsTorch(
                    mask_block_cnt=cuda_k_mask_cnt,
                    mask_block_offset=cuda_k_mask_offset,
                    mask_block_idx=cuda_k_mask_idx,
                    full_block_cnt=cuda_k_full_cnt,
                    full_block_offset=cuda_k_full_offset,
                    full_block_idx=cuda_k_full_idx,
                    # The fwd path (and the dq half of bwd) sets q_stage=2 on sm100,
                    # so base_m_block = q_stage * tile_m = sparse_tile_m. Declare the
                    # block size explicitly so the new FA backend doesn't have to infer
                    # it (which fails when seqlen_q <= sparse_tile_m gives only 1 q-block).
                    block_size=(sparse_tile_m, tile_n),
                )
            with nvtx.add_nvtx_event(
                f"create_k2q_csr_sparse_from_func-"
                f"seqlen_q={self.seqlen_q}-seqlen_k={self.seqlen_k}-"
                f"tile_m={tile_m}-tile_n={tile_n}"
            ):
                # K2Q (Backward): fix kv_block, loop q_blocks
                (
                    cuda_q_mask_cnt,
                    cuda_q_mask_offset,
                    cuda_q_mask_idx,
                    cuda_q_full_cnt,
                    cuda_q_full_offset,
                    cuda_q_full_idx,
                ) = create_block_mask_cuda.create_k2q_csr_sparse_from_func(
                    hstu_func,
                    self.seqlen_q,
                    self.seqlen_k,
                    Q_BLOCK_SIZE=bwd_sparse_tile_m,
                    KV_BLOCK_SIZE=bwd_sparse_tile_n,
                )

                linear_q_block_sparse_mask = LinearBlockSparseTensorsTorch(
                    mask_block_cnt=cuda_q_mask_cnt,
                    mask_block_offset=cuda_q_mask_offset,
                    mask_block_idx=cuda_q_mask_idx,
                    full_block_cnt=cuda_q_full_cnt,
                    full_block_offset=cuda_q_full_offset,
                    full_block_idx=cuda_q_full_idx,
                    # Match the K2Q CSR block to the selected backward attention tile.
                    block_size=(bwd_sparse_tile_m, bwd_sparse_tile_n),
                )
        else:
            # Prepare mask_mod
            def mask_mod_flex(b, h, q_idx, kv_idx, arbitrary_func=hstu_func):
                return flex_arbitrary_mask(b, h, q_idx, kv_idx, arbitrary_func)

            # Preare linear block sparse mask of k for forward
            bm = create_block_mask(
                mask_mod_flex,
                1,
                1,
                self.seqlen_q,
                self.seqlen_k,
                device="cuda",
                BLOCK_SIZE=(sparse_tile_m, tile_n),
            )
            _, _, k_mask_cnt, k_mask_idx, k_full_cnt, k_full_idx, *_ = bm.as_tuple()
            k_block_sparse_mask = BlockSparseTensorsTorch(
                mask_block_cnt=k_mask_cnt,
                mask_block_idx=k_mask_idx,
                full_block_cnt=k_full_cnt,
                full_block_idx=k_full_idx,
            )
            linear_k_block_sparse_mask = bhqk_to_linear_sparse_tensors(
                k_block_sparse_mask
            )

            # Preare linear block sparse mask of q for backward
            bm_bwd = create_block_mask(
                mask_mod_flex,
                1,
                1,
                self.seqlen_q,
                self.seqlen_k,
                device="cuda",
                BLOCK_SIZE=(bwd_sparse_tile_m, bwd_sparse_tile_n),
            )
            (
                _,
                _,
                _,
                _,
                _,
                _,
                q_mask_cnt,
                q_mask_idx,
                q_full_cnt,
                q_full_idx,
                *_,
            ) = bm_bwd.as_tuple()
            q_block_sparse_mask = BlockSparseTensorsTorch(
                mask_block_cnt=q_mask_cnt,
                mask_block_idx=q_mask_idx,
                full_block_cnt=q_full_cnt,
                full_block_idx=q_full_idx,
            )
            linear_q_block_sparse_mask = bhqk_to_linear_sparse_tensors(
                q_block_sparse_mask
            )

        # Prepare FA4 args for both forward and backward
        return dict(
            linear_k_block_sparse_mask=linear_k_block_sparse_mask,
            linear_q_block_sparse_mask=linear_q_block_sparse_mask,
            aux_tensors=aux_tensors,
        )

    def _transfer_ffa_args_to_fa4_args(self) -> None:
        if self.skip_attn_fwd:
            self.fa4_fwd_args_dict = {}
            self.fa4_bwd_args_dict = {}
            self.n_func = 0
            return

        # Compute upper bound of func count for buffer allocation
        n_ub_func = 2 * len(self.k_ranges) + 1

        # Transfer representation of attn mask from AttnSlice to HSTU Functions
        # where hstu_func: shape=(n_func, sq), and unsqueeze to (1, 1, n_func, sq) to be broadcastable
        with nvtx.add_nvtx_event(
            f"magi_to_hstu-"
            f"seqlen_q={self.seqlen_q}-seqlen_k={self.seqlen_k}-"
            f"n_ub_func={n_ub_func}"
        ):
            hstu_func = magi_to_hstu_cuda.magi_to_hstu(
                q_ranges=self.ffa_fwd_args_dict["q_ranges"],
                k_ranges=self.ffa_fwd_args_dict["k_ranges"],
                mask_types=self.ffa_fwd_args_dict["attn_type_map"],
                seqlen_q=self.seqlen_q,
                seqlen_k=self.seqlen_k,
                n_max_func=n_ub_func,
            )

            # Get actual func count from sliced output
            self.n_func = hstu_func.size(0)

            hstu_func = hstu_func.unsqueeze(0).unsqueeze(0)

        # Pad hstu_func to avoid out-of-bounds access in FA4 kernels
        from magi_attention.api.functools import pad_at_dim

        hstu_func = pad_at_dim(
            hstu_func,
            dim=-1,
            pad_size=2 * max(self.tile_m, self.tile_m_bwd),
            value=0,
        )
        aux_tensors = [hstu_func]

        # Sanity check: convert hstu mask and attn slice to qxk bitmap mask
        if env.general.is_sanity_check_enable():
            # Path 1: mask from FFA args directly
            mask_from_ffa = make_attn_mask_from_ffa_args(
                q_ranges=self.q_ranges,
                k_ranges=self.k_ranges,
                attn_type_map=self.attn_type_map,
                total_seqlen_q=self.seqlen_q,
                total_seqlen_k=self.seqlen_k,
                device=hstu_func.device,
            )

            # Path 2: mask from hstu_func (before padding)
            # hstu_func shape: [1, 1, n_max_func, seqlen_q], squeeze to [n_max_func, seqlen_q]
            hstu_func_squeezed = hstu_func.squeeze(0).squeeze(0)[:, : self.seqlen_q]
            mask_from_func = self.func_to_mask(hstu_func_squeezed, self.seqlen_k)
            # Compare the two masks
            if not torch.equal(mask_from_ffa, mask_from_func):
                diff_count = (mask_from_ffa != mask_from_func).sum().item()
                # Find first mismatch position
                mismatch_indices = (mask_from_ffa != mask_from_func).nonzero(
                    as_tuple=False
                )
                assert len(mismatch_indices) > 0
                first_mismatch = mismatch_indices[0]
                q_idx, k_idx = first_mismatch[0].item(), first_mismatch[1].item()

                raise RuntimeError(
                    f"magi_to_hstu conversion mismatch! {diff_count} positions differ, "
                    f"where:\n      {self.q_ranges=}\n      {self.k_ranges=}\n      {self.attn_type_map=}\n"
                    f"      {self.n_func=}\n"
                    f"      with the first mismatch at position: {q_idx=}, {k_idx=}, "
                    f"ffa={mask_from_ffa[q_idx, k_idx].item()}, "
                    f"func={mask_from_func[q_idx, k_idx].item()}"
                )

        self.fa4_fwd_args_dict = self._make_fa4_args_dict(
            hstu_func=hstu_func,
            aux_tensors=aux_tensors,
            tile_m=self.tile_m,
            tile_n=self.tile_n,
        )
        if (self.tile_m_bwd, self.tile_n_bwd) == (self.tile_m, self.tile_n):
            self.fa4_bwd_args_dict = self.fa4_fwd_args_dict
        else:
            self.fa4_bwd_args_dict = self._make_fa4_args_dict(
                hstu_func=hstu_func,
                aux_tensors=aux_tensors,
                tile_m=self.tile_m_bwd,
                tile_n=self.tile_n_bwd,
            )

    def to_fa4_args(self, is_bwd: bool = False) -> dict:
        return self.fa4_bwd_args_dict if is_bwd else self.fa4_fwd_args_dict

    def to_ffa_args(self, is_bwd: bool = False) -> dict:
        raise RuntimeError("FA4AttnArg does not support to_ffa_args")

    @classmethod
    def func_to_mask(cls, func: torch.Tensor, seqlen_k: int) -> torch.Tensor:
        """
        Convert func array to 2D attention mask.

        Args:
            func: shape [n_max_func, seqlen_q], contains interval boundaries
            seqlen_k: sequence length of K

        Returns:
            mask: shape [seqlen_q, seqlen_k], True means can attend

        Encoding rule:
            interval 0: [0, F0)
            interval 1: [F1, F2)
            interval 2: [F3, F4)
            ...
        """
        n_max_func, seqlen_q = func.shape
        device = func.device

        # k indices for broadcasting: [1, seqlen_k]
        k_indices = torch.arange(seqlen_k, device=device).unsqueeze(0)

        # Initialize mask
        mask = torch.zeros(seqlen_q, seqlen_k, dtype=torch.bool, device=device)

        # Process first interval: [0, F0)
        F0 = func[0].unsqueeze(1)  # [seqlen_q, 1]
        """
            Assuming seqlen_q = 4, seqlen_k = 8, func[0] = [3, 5, 2, 6]  # F0 value for each q
            k_indices [1, seqlen_k] broadcasted along rows, F0 [seqlen_q, 1] broadcasted along columns
            k_indices [1, 8]:  [[0, 1, 2, 3, 4, 5, 6, 7]]
                            ↓ copied 4 rows
                    [[0, 1, 2, 3, 4, 5, 6, 7],
                        [0, 1, 2, 3, 4, 5, 6, 7],
                        [0, 1, 2, 3, 4, 5, 6, 7],
                        [0, 1, 2, 3, 4, 5, 6, 7]]

            F0 [4, 1]:         [[3],       → copied 8 columns → [[3, 3, 3, 3, 3, 3, 3, 3],
                                [5],                     [5, 5, 5, 5, 5, 5, 5, 5],
                                [2],                     [2, 2, 2, 2, 2, 2, 2, 2],
                                [6]]                     [6, 6, 6, 6, 6, 6, 6, 6]]

                            k=0  k=1  k=2  k=3  k=4  k=5  k=6  k=7
                    ┌────┬────┬────┬────┬────┬────┬────┬────┐
            q0 (F0=3) │ T  │ T  │ T  │ F  │ F  │ F  │ F  │ F  │  → [0,3) visible
                    ├────┼────┼────┼────┼────┼────┼────┼────┤
            q1 (F0=5) │ T  │ T  │ T  │ T  │ T  │ F  │ F  │ F  │  → [0,5) visible
                    ├────┼────┼────┼────┼────┼────┼────┼────┤
            q2 (F0=2) │ T  │ T  │ F  │ F  │ F  │ F  │ F  │ F  │  → [0,2) visible
                    ├────┼────┼────┼────┼────┼────┼────┼────┤
            q3 (F0=6) │ T  │ T  │ T  │ T  │ T  │ T  │ F  │ F  │  → [0,6) visible
        """
        mask |= k_indices < F0

        # Process remaining intervals: [F_{2i+1}, F_{2i+2}) for i = 0, 1, ...
        for i in range((n_max_func - 1) // 2):
            start_idx = 2 * i + 1
            end_idx = 2 * i + 2
            if end_idx >= n_max_func:
                break

            F_start = func[start_idx].unsqueeze(1)  # [seqlen_q, 1]
            F_end = func[end_idx].unsqueeze(1)  # [seqlen_q, 1]

            mask |= (k_indices >= F_start) & (k_indices < F_end)

        return mask

    @classmethod
    def _print_nonzero_by_col(cls, tensor: torch.Tensor, name: str = "tensor") -> None:
        """
        Print non-zero elements by column.
        Assuming tensor shape: [1, 1, nfunc, seq_len] or [nfunc, seq_len]
        """
        # Remove leading dimensions, keep only [nfunc, seq_len]
        t = tensor.squeeze()
        if t.dim() == 1:
            t = t.unsqueeze(0)

        nfunc, seq_len = t.shape

        print(f"=== {name} nonzero values (shape: {tensor.shape}) ===", flush=True)

        for col in range(seq_len):
            col_data = t[:, col]
            nonzero_mask = col_data != 0
            if nonzero_mask.any():
                nonzero_rows = nonzero_mask.nonzero(as_tuple=True)[0]
                entries = [
                    f"row {row.item()} = {col_data[row].item()}" for row in nonzero_rows
                ]
                print(f"col {col}: {', '.join(entries)}", flush=True)

    def __repr__(self) -> str:  # pragma: no cover
        indent = ""
        repr_str = "FA4AttnArg(\n"

        # Base class fields
        base_repr_lines = super().__repr__().splitlines()
        for line in base_repr_lines[1:-1]:  # Skip the first and last lines
            repr_str += f"{indent}    {line}\n"

        # FA4 specific fields
        repr_str += f"{indent}    tile_m={self.tile_m},\n"
        repr_str += f"{indent}    tile_n={self.tile_n},\n"
        repr_str += f"{indent}    tile_m_bwd={self.tile_m_bwd},\n"
        repr_str += f"{indent}    tile_n_bwd={self.tile_n_bwd},\n"
        repr_str += f"{indent}    seqlen_q={self.seqlen_q},\n"
        repr_str += f"{indent}    seqlen_k={self.seqlen_k},\n"
        repr_str += f"{indent}    headdim={self.headdim},\n"
        repr_str += f"{indent}    headdim_v={self.headdim_v},\n"
        repr_str += f"{indent}    n_func={self.n_func},\n"

        repr_str += f"{indent}    # Generated by _transfer_ffa_args_to_fa4_args:\n"
        repr_str += format_dict_field(
            "fa4_fwd_args_dict", self.fa4_fwd_args_dict, indent
        )
        repr_str += format_dict_field(
            "fa4_bwd_args_dict", self.fa4_bwd_args_dict, indent
        )

        repr_str = repr_str.rstrip(",\n") + "\n)"
        return repr_str


@dataclass(repr=False)
class CalcMeta:
    local_attn_arg: AttnArg
    remote_attn_args_list: list[AttnArg]

    # If True, merge local + remote args into a single attn_arg for no-overlap mode
    no_overlap: bool = False

    # Specific meta for FA4 backend
    headdim: int = 128
    headdim_v: int | None = None
    seqlen_q_shard: int = 0  # local q seqlen from dispatch_meta
    seqlen_k_local: int = 0  # for local_attn_arg
    seqlen_k_per_remote_stage: list[int] = field(
        default_factory=list
    )  # for remote_attn_args_list
    # Q-heads-per-KV-head ratio. Used by the FA4 path to match the cute backend's
    # `q_stage` heuristic when building the block-sparse mask. Default 1 (MHA).
    qhead_per_kvhead: int = 1

    @property
    def overlap_degree(self) -> int:
        return len(self.remote_attn_args_list)

    def __post_init__(self):
        assert (
            self.overlap_degree >= 0
        ), f"Overlap degree must be >= 0, but got {self.overlap_degree=}"

        if env.general.kernel_backend() == MagiAttentionKernelBackend.FA4:
            assert len(self.seqlen_k_per_remote_stage) == self.overlap_degree, (
                f"seqlen_k_per_remote_stage length must match overlap_degree, "
                f"got {len(self.seqlen_k_per_remote_stage)=} vs {self.overlap_degree=}"
            )

            fwd_tile_size, bwd_tile_size = self._resolve_fa4_tile_sizes()
            fwd_tile_m, fwd_tile_n = fwd_tile_size
            bwd_tile_m, bwd_tile_n = bwd_tile_size

            # DEVIATION: local_attn_arg (AttnArg) is replaced with FA4AttnArg instance
            # Reason: FA4 backend requires tile-size-aware args with block-sparse mask
            #   metadata that plain AttnArg does not carry.
            # Recovery: none — the original AttnArg fields are forwarded into FA4AttnArg.
            self.local_attn_arg = FA4AttnArg(
                q_ranges=self.local_attn_arg.q_ranges,
                k_ranges=self.local_attn_arg.k_ranges,
                attn_type_map=self.local_attn_arg.attn_type_map,
                total_area=self.local_attn_arg.total_area,
                tile_m=fwd_tile_m,
                tile_n=fwd_tile_n,
                tile_m_bwd=bwd_tile_m,
                tile_n_bwd=bwd_tile_n,
                seqlen_q=self.seqlen_q_shard,
                seqlen_k=self.seqlen_k_local,
                headdim=self.headdim,
                headdim_v=self.headdim_v,
                qhead_per_kvhead=self.qhead_per_kvhead,
            )
            # DEVIATION: remote_attn_args_list entries (AttnArg) replaced with FA4AttnArg
            # Reason: same as local_attn_arg above — FA4 backend requirement.
            # Recovery: none — original AttnArg fields are forwarded.
            for stage in range(self.overlap_degree):
                remote_attn_arg = self.remote_attn_args_list[stage]
                self.remote_attn_args_list[stage] = FA4AttnArg(
                    q_ranges=remote_attn_arg.q_ranges,
                    k_ranges=remote_attn_arg.k_ranges,
                    attn_type_map=remote_attn_arg.attn_type_map,
                    total_area=remote_attn_arg.total_area,
                    tile_m=fwd_tile_m,
                    tile_n=fwd_tile_n,
                    tile_m_bwd=bwd_tile_m,
                    tile_n_bwd=bwd_tile_n,
                    seqlen_q=self.seqlen_q_shard,
                    seqlen_k=self.seqlen_k_per_remote_stage[stage],
                    headdim=self.headdim,
                    headdim_v=self.headdim_v,
                    qhead_per_kvhead=self.qhead_per_kvhead,
                )

        if self.no_overlap and self.overlap_degree > 0:
            self.merged_attn_arg: AttnArg | None = self.make_merged_attn_arg(
                local_kv_seqlen=self.seqlen_k_local,
            )
        else:
            self.merged_attn_arg = None

    def make_merged_attn_arg(self, local_kv_seqlen: int) -> AttnArg:
        """Merge local_attn_arg and all remote_attn_args into a single AttnArg.

        In no-overlap mode, remote KV is concatenated after local KV.
        The remote k_ranges need to be offset by ``local_kv_seqlen``
        so that they point into the concatenated K tensor.

        Args:
            local_kv_seqlen: the sequence length of local K tensor
                (i.e. the K-only seqlen, NOT the fused KV seqlen)

        Returns:
            A single AttnArg covering both local and remote attention slices.
        """
        merged_q_ranges = AttnRanges.from_ranges(list(self.local_attn_arg.q_ranges))
        merged_k_ranges = AttnRanges.from_ranges(list(self.local_attn_arg.k_ranges))
        merged_attn_type_map = list(self.local_attn_arg.attn_type_map)
        merged_total_area = self.local_attn_arg.total_area

        for remote_arg in self.remote_attn_args_list:
            if remote_arg.can_skip(is_bwd=False):
                continue
            for q_range in remote_arg.q_ranges:
                merged_q_ranges.append(q_range)
            for k_range in remote_arg.k_ranges:
                merged_k_ranges.append(
                    AttnRange(
                        k_range.start + local_kv_seqlen,
                        k_range.end + local_kv_seqlen,
                    )
                )
            merged_attn_type_map.extend(remote_arg.attn_type_map)
            if remote_arg.total_area >= 0 and merged_total_area >= 0:
                merged_total_area += remote_arg.total_area
            else:
                merged_total_area = -1

        if isinstance(self.local_attn_arg, FA4AttnArg):
            merged_seqlen_k = local_kv_seqlen + sum(self.seqlen_k_per_remote_stage)
            return FA4AttnArg(
                q_ranges=merged_q_ranges,
                k_ranges=merged_k_ranges,
                attn_type_map=merged_attn_type_map,
                total_area=merged_total_area,
                tile_m=self.local_attn_arg.tile_m,
                tile_n=self.local_attn_arg.tile_n,
                tile_m_bwd=self.local_attn_arg.tile_m_bwd,
                tile_n_bwd=self.local_attn_arg.tile_n_bwd,
                seqlen_q=self.seqlen_q_shard,
                seqlen_k=merged_seqlen_k,
                headdim=self.headdim,
                headdim_v=self.headdim_v,
                qhead_per_kvhead=self.qhead_per_kvhead,
            )

        return AttnArg(
            q_ranges=merged_q_ranges,
            k_ranges=merged_k_ranges,
            attn_type_map=merged_attn_type_map,
            total_area=merged_total_area,
        )

    def _resolve_fa4_tile_sizes(self) -> tuple[tuple[int, int], tuple[int, int]]:
        return (
            _resolve_tile_sizes("forward", self.headdim),
            _resolve_tile_sizes("backward", self.headdim),
        )

    def __repr__(self) -> str:  # pragma: no cover
        indent = ""
        repr_str = f"CalcMeta(overlap_degree={self.overlap_degree},\n"

        # local_attn_arg
        local_attn_arg_repr_lines = repr(self.local_attn_arg).splitlines()
        repr_str += f"{indent}    local_attn_arg={local_attn_arg_repr_lines[0]}\n"
        for line in local_attn_arg_repr_lines[1:]:
            repr_str += f"{indent}    {line}\n"

        # remote_attn_args_list
        repr_str += format_list_field(
            "remote_attn_args_list", self.remote_attn_args_list, indent
        )

        repr_str = repr_str.rstrip(",\n") + "\n)"
        return repr_str
